### ISSUE TITLE
recently compiled/generated selection in home tab

### ISSUE THREAD

**Issue by ghost** [AndersonMamede/scriptcase-tools#6]
Please incorporate recently compiled/generated selection in home tab as we all are facing problem in deployment of application which are recently changed and this is very tedious when our project span across multiple folder as there is no sort/filter function in scriptcase home like application changed today

**Comment by AndersonMamede** [comment]
Hi there!

Let me make sure I understand you correctly...
What do you mean? An option to select all applications which were changed on the current day?

**Comment by AndersonMamede** [comment]
As there is no follow up, I'm closing it.
Thank you.
