### ISSUE TITLE
export grid using wkhtmltopdf, can not make pdf (Production on Centos 8)

### ISSUE THREAD

**Issue by myslts** [AndersonMamede/scriptcase-tools#8]
I deployed my scriptcase apps on Centos 8 as the production machine. This time is the second time.
I found out that after deploy scriptcase, the export to pdf feature always does not work. **In my previous deployment, I install wkhtmltopdf 0.12.5 (with patched qt), then I copied /usr/local/bin/wkhtmltopdf to /var/www/html/_lib/prod/third/wkhtmltopdf/linux-amd64/wkhtmltopdf-amd64 and it works well.**

But, this time on my second deployment on other Centos 8 server. After deploy the apps, I checked that export grid to pdf get problem, **so I did the same thing like what I've done before, but this time it's still shows error.**
It could not produce pdf file.  **If I run the command on file .log**, it shows like this:
_**Error: Failed to load http://url:81/folder_name/_lib/tmp/sc_grid_lokasi_layanan_html_nf956kn6oudbmqstc48trkljhk.html, with network status code 1 and http status code 0 - Connection refused
Error: Failed loading page http://url:81/folder_name/_lib/tmp/sc_grid_lokasi_layanan_html_nf956kn6oudbmqstc48trkljhk.html (sometimes it will work just to ignore this error with --load-error-handling ignore)
Exit with code 1 due to network error: ConnectionRefusedError**_

I try many things, but it still does not make pdf file and showing error. Do you have any suggestions?

**Comment by AndersonMamede** [comment]
Hi @myslts ,

This repository is related only with ScriptCase Tools, a non-official web extension, it's in no way related with Scriptcase itself nor with NetMake, so unfortunately I am not able to help you.
